env:
    global:
        - ANDROID_API_LEVEL=28
        - ANDROID_BUILD_TOOLS_VERSION=28.0.3

language: android
android:
    components:
        - tools
        - tools
        - platform-tools
        - build-tools-$ANDROID_BUILD_TOOLS_VERSION
        - android-$ANDROID_API_LEVEL
        - extra-google-m2repository
        - extra-android-m2repository
jdk:
    - oraclejdk8

before_install:
    - echo yes | sdkmanager "platforms;android-28"

script:
  - ./editor/gradlew build check --stacktrace
